### ISSUE TITLE
trying to test

### ISSUE THREAD

**Issue by PavelPolyakov** [pyr/check-graphite#12]
~~~
./bin/check_graphite 
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- check_graphite (LoadError)
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from ./bin/check_graphite:3:in `<main>'
~~~

is that ok?

**Comment by joelgriffiths** [comment]
You have to install the gem:

$  git clone https://github.com/pyr/check-graphite.git
$  cd check-graphite/
$  gem build check_graphite.gemspec
$  sudo gem install check_graphite-0.2.5.gem
