### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by drpain** [pyr/check-graphite#17]
I installed it using ``sudo gen install check_graphite``, but when I try and run the command I get the following syntax error:

```shelll
/usr/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:36:in `gem_original_require': /var/lib/gems/1.8/gems/nagios_check-0.3.0/lib/nagios_check/range.rb:23: syntax error, unexpected kNOT (SyntaxError)
      @inverse ? not(result) : result
                    ^
/var/lib/gems/1.8/gems/nagios_check-0.3.0/lib/nagios_check/range.rb:23: syntax error, unexpected ':', expecting kEND
      @inverse ? not(result) : result
                              ^
	from /usr/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:36:in `require'
	from /var/lib/gems/1.8/gems/nagios_check-0.3.0/lib/nagios_check.rb:6
	from /usr/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:36:in `gem_original_require'
	from /usr/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:36:in `require'
	from /var/lib/gems/1.8/gems/check_graphite-0.2.5/lib/check_graphite.rb:1
	from /usr/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:36:in `gem_original_require'
	from /usr/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:36:in `require'
	from /var/lib/gems/1.8/gems/check_graphite-0.2.5/bin/check_graphite:3
	from /usr/local/bin/check_graphite:19:in `load'
	from /usr/local/bin/check_graphite:19
```

I don't know ruby very well, how do I go about fixing this?

**Comment by nutcr4cker** [comment]
I think its because of your ruby version ->  try 1.9 or above. Or try change not in this file to ! sign,
